production:
    domain: api.ebay.com
    appid: <something>
    devid: <something>
    certid: <something>
    redirecturi: <something>
    marketplace: EBAY_RU
    listing_policies:
        fulfillment_policy_id: <something>
        payment_policy_id: <something>
        return_policy_id: <something>
    location_key: <something>
    
sandbox:
    domain: api.sandbox.ebay.com
    appid: <something>
    devid: <something>
    certid: <something>
    redirecturi: <something>
    marketplace: EBAY_RU
    listing_policies:
        fulfillment_policy_id: <something>
        payment_policy_id: <something>
        return_policy_id: <something>
    location_key: <something>
